import = ["~/.config/alacritty/themes/themes/pencil_dark.toml"]

[env]
TERM = "xterm-256color"

[window]
padding.x = 6
padding.y = 6

decorations = "Buttonless"

opacity = 0.9
blur = true
option_as_alt = "Both"

startup_mode = "Fullscreen"

[font]
normal.family = "MesloLGS Nerd Font Mono"

size = 18
